"""Final report stage — generate translation_report.md."""
import json
from pathlib import Path
from datetime import datetime


def run(workspace: Path, **kwargs) -> dict:
    """
    Generate translation_report.md with full pipeline summary.

    Args:
        workspace: Workspace directory Path

    Returns:
        dict with report generation results
    """
    from translator.state.manifest import Manifest
    from translator.state.status import PipelineStatus

    manifest = Manifest.load(workspace)
    status = PipelineStatus.load(workspace)

    # Load QA findings
    qa_path = workspace / "state" / "qa_findings.json"
    qa_data = {"findings": []}
    if qa_path.exists():
        with open(qa_path, 'r', encoding='utf-8') as f:
            qa_data = json.load(f)

    # Load chunk stats
    chunk_index_path = workspace / "state" / "chunk_index.json"
    chunk_stats = {"total": 0, "translated": 0}
    if chunk_index_path.exists():
        with open(chunk_index_path, 'r', encoding='utf-8') as f:
            chunk_data = json.load(f)
            chunk_stats = chunk_data.get("stats", {})

    # Load export results
    export_path = workspace / "state" / "export_results.json"
    export_results = []
    if export_path.exists():
        with open(export_path, 'r', encoding='utf-8') as f:
            export_results = json.load(f).get("exports", [])

    # Build report
    lines = [
        "# Translation Report",
        "",
        f"**Document**: {manifest.input_path.name}",
        f"**Project**: {manifest.project_slug}",
        f"**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"**Pipeline version**: {manifest.version}",
        "",
        "## Status",
        f"- **Overall**: {status.data.get('overall_status', 'UNKNOWN')}",
        f"- **Source language**: {manifest.source_lang}",
        f"- **Target language**: {manifest.target_lang}",
        "",
        "## Pipeline Stages",
        ""
    ]

    for stage, data in status.data.get("stages", {}).items():
        stage_status = data.get("status", "unknown")
        lines.append(f"- {stage}: **{stage_status}**")

    lines.extend([
        "",
        "## Statistics",
        f"- Source file size: {manifest.original_size:,} bytes",
        f"- Total chunks: {chunk_stats.get('total', 'N/A')}",
        f"- Translated chunks: {chunk_stats.get('translated', 'N/A')}",
        f"- Failed chunks: {chunk_stats.get('failed', 'N/A')}",
        "",
        "## QA Summary",
    ])

    qa_summary = qa_data.get("summary", {})
    critical = qa_summary.get("critical", 0)
    warnings = qa_summary.get("warnings", 0)

    if critical > 0:
        lines.append(f"- **CRITICAL issues**: {critical}")
    if warnings > 0:
        lines.append(f"- **Warnings**: {warnings}")
    if critical == 0 and warnings == 0:
        lines.append("- No issues found")

    lines.extend([
        "",
        "## Exports",
    ])

    for exp in export_results:
        fmt = exp.get("format", "?")
        st = exp.get("status", "?")
        if st == "success":
            lines.append(f"- .{fmt}: **success**")
        else:
            err = exp.get("error", "unknown")
            lines.append(f"- .{fmt}: **failed** — {err}")

    # Warnings from status
    if status.data.get("warnings"):
        lines.extend(["", "## Warnings"])
        for warn in status.data["warnings"]:
            lines.append(f"- {warn.get('warning', 'Unknown warning')}")

    # Errors from status
    if status.data.get("errors"):
        lines.extend(["", "## Errors"])
        for err in status.data["errors"]:
            lines.append(f"- [{err.get('stage', '?')}] {err.get('error', 'Unknown error')}")

    lines.extend([
        "",
        "---",
        f"*Generated by Hermes Universal RU Document Translator v{manifest.version}*"
    ])

    report_text = '\n'.join(lines)

    # Save report
    report_path = workspace / "output" / "translation_report.md"
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(report_text)

    return {
        "status": "completed",
        "report_path": str(report_path),
        "overall_status": status.data.get("overall_status", "UNKNOWN")
    }


if __name__ == "__main__":
    from pathlib import Path
    import sys
    if len(sys.argv) < 2:
        print("Usage: python final_report.py <workspace>")
        sys.exit(1)
    result = run(Path(sys.argv[1]))
    print(result)